-- ===========================
-- TABELA: VEICULO
-- ===========================
CREATE TABLE IF NOT EXISTS VEICULO (
    VEICULOID INTEGER PRIMARY KEY AUTOINCREMENT,
    MODELO TEXT NOT NULL,
    PLACA TEXT NOT NULL UNIQUE,
    CONSUMO_MEDIO DECIMAL(4,2) NOT NULL,
    CARGA_MAXIMA DECIMAL(7,2)
);

-- ===========================
-- TABELA: MOTORISTA
-- ===========================
CREATE TABLE IF NOT EXISTS MOTORISTA (
    MOTORISTAID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL,
    CNH TEXT NOT NULL UNIQUE,
    TELEFONE TEXT NOT NULL,
    Ativo INTEGER DEFAULT 1
);

-- ===========================
-- TABELA: ROTA
-- ===========================
CREATE TABLE IF NOT EXISTS ROTA (
    ROTAID INTEGER PRIMARY KEY AUTOINCREMENT,
    ORIGEM TEXT NOT NULL,
    DESTINO TEXT NOT NULL,
    DISTANCIA REAL NOT NULL
);

-- ===========================
-- TABELA: PRECO_COMBUSTIVEL
-- ===========================
CREATE TABLE IF NOT EXISTS PRECO_COMBUSTIVEL (
    PRECOID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMBUSTIVEL TEXT NOT NULL,
    PRECO REAL NOT NULL,
    DATA_CONSULTA DATETIME
);

-- ===========================
-- TABELA: VIAGEM
-- ===========================
CREATE TABLE IF NOT EXISTS VIAGEM (
    VIAGEMID INTEGER PRIMARY KEY AUTOINCREMENT,
    VEICULOID INTEGER NOT NULL,
    MOTORISTAID INTEGER NOT NULL,
    ROTAID INTEGER NOT NULL,
    DATA_SAIDA DATETIME,
    DATA_CHEGADA DATETIME,
    SITUACAO TEXT NOT NULL,
    FOREIGN KEY (VEICULOID) REFERENCES VEICULO(VEICULOID),
    FOREIGN KEY (MOTORISTAID) REFERENCES MOTORISTA(MOTORISTAID),
    FOREIGN KEY (ROTAID) REFERENCES ROTA(ROTAID)
);
